- name: Create postgres backup directory
  ansible.builtin.file:
    path: "/var/lib/postgresql/backup"
    state: directory
    owner: postgres
    group: postgres

- name: Create cron for postgres database dump
  ansible.builtin.cron:
    name: postgres_backup_dump
    user: postgres
    minute: "15"
    job: "pg_dump mastodon > /var/lib/postgresql/backup/mastodon.sql"

- name: Create cron for postgres database backup via restic
  ansible.builtin.cron:
    name: postgres_backup_restic
    user: root
    minute: "50"
    job: "ionice -c2 nice -n19 restic -r s3:https://{{ restic_s3_hostname }}/{{ restic_s3_bucket }} backup /var/lib/postgresql/backup"
