---
- name: Restart prometheus-node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted

- name: Restart syslog
  ansible.builtin.service:
    name: syslog
    state: restarted
