- name: Check if mastodon database exists
  ignore_errors: true
  changed_when: false
  no_log: true
  postgresql_ping:
    db: mastodon
    login_host: "{{ groups['postgresql'][0] }}"
    login_user: mastodon
    login_password: "{{ postgres_password }}"
  register: mastodon_database
  
- name: Gather the package facts
  ansible.builtin.package_facts:

- name: Run db pre-migrate before version upgrade
  ansible.builtin.command: bundle exec rails db:migrate
  args:
    chdir: /opt/mastodon
  become_user: mastodon
  environment:
    RAILS_ENV: production
    DB_HOST: "{{ groups['postgresql'][0] }}"
    DB_PORT: "5432"
    SKIP_POST_DEPLOYMENT_MIGRATIONS: "true"
  when: "mastodon_database.is_available and 'mastodon-core' in ansible_facts.packages and ansible_facts.packages['mastodon-core'][0].version != mastodon_app_version"
