---
- ansible.builtin.import_tasks: user.yml

- name: Create config directory
  ansible.builtin.file:
    path: /etc/mastodon
    state: directory
    owner: mastodon
    group: mastodon

- ansible.builtin.import_tasks: nodejs.yml
- ansible.builtin.import_tasks: pgbouncer.yml

- ansible.builtin.include_tasks: monitoring.yml
  when: "'monitoring_server' in groups"

- ansible.builtin.include_tasks: mount.yml
  when: mastodon_app_mount_src is defined

- name: Download mastodon-core deb
  ansible.builtin.get_url:
    url: https://github.com/laszlovl/mastodon-build/releases/download/v{{ mastodon_app_version }}/mastodon-core_{{ mastodon_app_version }}_amd64.deb
    checksum: sha256:{{ mastodon_app_deb_hash }}
    dest: /var/tmp/

- name: Install mastodon core
  ansible.builtin.apt:
    deb: /var/tmp/mastodon-core_{{ mastodon_app_version }}_amd64.deb
  register: mastodon_app_deb_result

- name: Install bundler
  ansible.builtin.command: gem install bundler
  args:
    creates: /usr/local/bin/bundle

- name: Install ansible dependencies
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present

- name: Create mastodon envfile
  ansible.builtin.template:
    src: env.j2
    dest: /etc/mastodon/env
  register: mastodon_app_envfile_result

- name: Symlink mastodon envfile
  ansible.builtin.file:
    src: /etc/mastodon/env
    dest: /opt/mastodon/.env
    state: link
    owner: mastodon
