---
- name: Create config directory
  ansible.builtin.file:
    path: /etc/mastodon
    state: directory
    owner: mastodon
    group: mastodon

- ansible.builtin.import_tasks: user.yml
- ansible.builtin.import_tasks: nodejs.yml
- ansible.builtin.import_tasks: pgbouncer.yml
- ansible.builtin.import_tasks: compile.yml

- ansible.builtin.include_tasks: monitoring.yml
  when: "'monitoring_server' in groups"

- ansible.builtin.include_tasks: mount.yml
  when: mastodon_app_mount_src is defined

- name: Install ansible dependencies
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present

- name: Create mastodon envfile
  ansible.builtin.template:
    src: env.j2
    dest: /etc/mastodon/env
  register: mastodon_app_envfile_result

- name: Symlink mastodon envfile
  ansible.builtin.file:
    src: /etc/mastodon/env
    dest: /opt/mastodon/.env
    state: link
    owner: mastodon
