---
- name: Add nodejs key
  ansible.builtin.apt_key:
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs repository
  ansible.builtin.apt_repository:
    repo: deb https://deb.nodesource.com/node_18.x jammy main
    state: present

- name: Install nodejs
  ansible.builtin.apt:
    name: nodejs
    update_cache: true

- name: Enable corepack
  ansible.builtin.command: corepack enable
  args:
    creates: /usr/bin/yarn
