---
- name: Install nftables
  ansible.builtin.apt:
    name: nftables
    state: present

- name: Create nftables directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/nftables
    - /etc/nftables/conf.d

- name: Create basic firewall config
  ansible.builtin.copy:
    src: nftables.conf
    dest: /etc/nftables.conf
  notify: Restart nftables

- name: Enable nftables service
  ansible.builtin.service:
    name: nftables
    enabled: true
