---
- ansible.builtin.include_role:
    name: mastodon_sidekiq
    tasks_from: instance.yml
  vars:
    instance_name: ingress
    queue: -q ingress,10 -q push -q pull -q default -q mailers
    concurrency: "{{ mastodon_sidekiq_ingress_concurrency }}"
