---
- name: Request SSL certificates
  ansible.builtin.include_role:
    name: nginx
    tasks_from: letsencrypt
  vars:
    domains:
      - "{{ mastodon_app_domain }}"
      - files.{{ mastodon_app_domain }}
      - assets.{{ mastodon_app_domain }}

- name: Add mastodon site to nginx
  ansible.builtin.template:
    src: site-mastodon.j2
    dest: /etc/nginx/sites-enabled/mastodon
  notify: Restart nginx

- name: Add nginx user to mastodon group
  ansible.builtin.user:
    name: www-data
    state: present
    groups: mastodon
    append: true
