---
# Values from https://pgtune.leopard.in.ua/ for 2 CPU cores and 2gb RAM
postgresql_max_connections: 200
postgresql_shared_buffers: 256MB
postgresql_effective_cache_size: 768MB
postgresql_maintenance_work_mem: 64MB
postgresql_checkpoint_completion_target: 0.9
postgresql_wal_buffers: 7864kB
postgresql_default_statistics_target: 100
postgresql_random_page_cost: 1.1
postgresql_effective_io_concurrency: 200
postgresql_work_mem: 655kB
postgresql_min_wal_size: 1GB
postgresql_max_wal_size: 4GB
