---
- name: Allow SSH in firewall
  ansible.builtin.include_role:
    name: firewall
    tasks_from: rule_allow
  vars:
    name: ssh
    port: "{{ base_ssh_port }}"

- name: Set SSH port
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^Port
    line: Port {{ base_ssh_port }}
  notify: Restart sshd

- name: Set SSH PermitRootLogin
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
  notify: Restart sshd

- name: Set SSH PasswordAuthentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
  notify: Restart sshd
