---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Enable systemd apt-daily.timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: started
    enabled: true

- name: Enable systemd apt-daily-upgrade.timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: started
    enabled: true

